In [100]:
import numpy as np

In [101]:
def sigmiod(x):
    return 1/(1+np.exp(-x))


In [102]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

In [103]:
np.random.seed(42)
W1 = np.random.random((2,2))
b1 = np.zeros((1,2))
W2 = np.random.random((2,1))
b2 = np.zeros((1,1))

In [104]:
learning_rate = 0.1
epochs = 10000

In [105]:
#训练网络
for epoch in range(epochs):
    #前向传播
    hidden_layer_input = np.dot(X,W1) + b1
    hidden_layer_output = sigmiod(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output,W2) + b2
    output_layer_output = sigmiod(output_layer_input)
    #反向传播
    output_error = (output_layer_output-y)*output_layer_output*(1-output_layer_output)
    hidden_layer_error = np.dot(output_error,W2.T)*hidden_layer_output*(1-hidden_layer_output)
    #更新权重和偏置
    W2 -= learning_rate*np.dot(hidden_layer_output.T,output_error)
    b2 -= learning_rate*np.sum(output_error,axis=0,keepdims=True)
    W1 -= learning_rate*np.dot(X.T,hidden_layer_error)
    b1 -= learning_rate*np.sum(hidden_layer_error,axis=0,keepdims=True) 

In [106]:
#损失函数计算方式
#loss = (np.mean((output_layer_output-y)**2))/2

In [107]:
#用训练好的模型进行预测
hidden_layer_input = np.dot(X,W1) + b1
hidden_layer_output = sigmiod(hidden_layer_input)
output_layer_input = np.dot(hidden_layer_output,W2) + b2
output_layer_output = sigmiod(output_layer_input)

In [108]:
#输出每个输入对应的计算数值
for i in range(len(X)):
    print(f"第{i}个输入",X[i])
    print(hidden_layer_input[i])
    print(hidden_layer_output[i])
    print(output_layer_input[i])
    print(output_layer_output[i])
    print(f"第{i}个输出",output_layer_output[i][0])
    print()


第0个输入 [0 0]
[-5.79319383 -2.42207539]
[0.00303897 0.08150475]
[-2.82718664]
[0.05587262]
第0个输出 0.055872619814252254

第1个输入 [0 1]
[-2.00974058  3.37124244]
[0.11818401 0.9667936 ]
[2.92135081]
[0.94889185]
第1个输出 0.9488918479227934

第2个输入 [1 0]
[-2.01442664  3.34924449]
[0.11769652 0.96608009]
[2.91994332]
[0.94882355]
第2个输出 0.948823546895149

第3个输入 [1 1]
[1.76902662 9.14256232]
[0.85433658 0.999893  ]
[-2.84483356]
[0.05494899]
第3个输出 0.054948992220017666



In [109]:
print('W1-----')
print(W1)
print('b1-----')
print(b1)

print('W2-----')
print(W2)
print('b2-----')
print(b2)

W1-----
[[3.77876719 5.77131988]
 [3.78345326 5.79331783]]
b1-----
[[-5.79319383 -2.42207539]]
W2-----
[[-8.17262084]
 [ 7.55637468]]
b2-----
[[-3.41823076]]
